language: node_js
node_js:
  - 14
install:
  - yarn
cache:
  directories:
    - node_modules
before_script:
  - yarn install
  - npm install -g codecov
script:
  - CI=false  yarn build
  - yarn test --coverage
after_success:
  - codecov --token=${{ secrets.CODECOV_TOKEN }}
