name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "======== ${{ github.event_name }}"
      - run: echo "======== ${{ secrets.CODECOV_TOKEN }}"
      - run: echo "======== ${{ runner.os }}"
      - run: echo "======== ${{ github.ref }}"
      - run: echo "======== ${{ github.repository }}"
      - run: echo "======== ${{ github.workspace }}"
      - run: echo "======= ${{ job.status }}"
